// <auto-generated />
namespace SNZY.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddedETFStockList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedETFStockList));
        
        string IMigrationMetadata.Id
        {
            get { return "202011201808162_Added-ETFStockList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
